### ISSUE TITLE
佬,10.0的系统没有适配吗

### ISSUE THREAD

**Issue by lydlovezjr** [fySpring/SimpleStepCounter#1]
我的小米8,10.0的系统.
运动步数一直是0

手上有6.0和7.0的测试机
是可以获取步数的

**Comment by fySpring** [comment]
现在已经适配android10了，是因为没有添加ACTIVITY_RECOGNITION权限导致

**Comment by lydlovezjr** [comment]
测试了一下,确实可以了.
给大佬点个赞.
