### ISSUE TITLE
退出应用杀死进程后不能记步

### ISSUE THREAD

**Issue by yihuangxing** [fySpring/SimpleStepCounter#3]
当打开应用时会记录实时显示步数。当退出应用杀死进程之后，不会记录步数。

**Comment by fySpring** [comment]
因为当前是根据保存的记录来累计步数，当被杀掉后再打开自然会从上次记录的步数开始增加。你可以在记录步数的同时，记录总的步数，通过总的步数来判断当前运动步数，这时你需要考虑日期因素。或者将其设为白名单或壁纸实现保活。
