### ISSUE TITLE
为什么关掉了 service，然后在打开app，步数会变成0

### ISSUE THREAD

**Issue by laukuansin** [fySpring/SimpleStepCounter#4]

**Comment by fySpring** [comment]
你是如何关掉Service？该现象是否必现？再打开是指重新启动还是从后台回到前台？你的设备系统是多少？其它设备是否也会出现该情况？请描述清楚谢谢~

**Comment by laukuansin** [comment]
我的设备是 huawei nova 3i，我只有一个手机测试， 好像触发一些错误就会自己关掉service 然后app也被关掉，然后在打开app是重新启动那个app，那个步数就会从0开始计算

**Comment by fySpring** [comment]
正常运行时是否可以统计到步数？现在的逻辑是统计到步数就会保存到数据库，打开APP会去查找数据库数据，如果你再打开时步数为0，就说明，步数没有被保存，请帮忙确定一下是什么情况导致的谢谢~

**Comment by laukuansin** [comment]
抱歉是我的疏忽，我已经可以正常统计步数了， 谢谢！！！
