### ISSUE TITLE
为什么这侦测步数有点敏感，好像我拿着手机只走 10步，但是那个步数显示20步后以上

### ISSUE THREAD

**Issue by laukuansin** [fySpring/SimpleStepCounter#5]

**Comment by fySpring** [comment]
我也测了下，确实比较敏感，你可以尝试下修改累计值。在 StepService.onSensorChanged 方法中，比如连续两次进入该方法，步数才累加1...

**Comment by laukuansin** [comment]
这样意思就是在service 加多一个counter，每天更新为0， 然后每一次进 onSensorChanged 就加1，然后 如果sensor 是detector就check看那个counter是不是可以被2除后才累加1 到步数？

**Comment by fySpring** [comment]
对，差不多是这个意思
